### ISSUE TITLE
Remove GitHub URL from dependency

### ISSUE THREAD

**Issue by achingbrain** [component/has-cors#1]
This library has a dependency on global but links to a tarball on GitHub - the same version of the global module is on NPM so do you think it you could update the package.json file to use that instead?

**Comment by TooTallNate** [comment]
The one on npm is actually a different code base. `component/global` isn't on npm IIRC.

That said, we could probably just remove the `global` module usage from here. I don't really remember why I added it and it seems redundant to me now.

**Comment by achingbrain** [comment]
Oops, you're quite right it is different, my apologies.  Removing the dependency would work too though.

**Comment by TooTallNate** [comment]
Pull request welcome!

**Comment by achingbrain** [comment]
I've submitted a pull request.  Let me know if it's not up to snuff.

**Comment by TooTallNate** [comment]
@defunctzombie Can you publish v1.1.0 to npm please? Thanks!

**Comment by defunctzombie** [comment]
@TooTallNate done, also added you as owner: https://www.npmjs.org/package/has-cors
